name: app
description: "template for Flutter and Dart Docker projects"
publish_to: "Application"
version: 0.1.0

environment:
  sdk: ">=3.4.0-212.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/favicon.ico
  - assets/favicon.png
  - .env
